### ISSUE TITLE
Output Protection signaling

### ISSUE THREAD

**Issue by lpiron** [Dash-Industry-Forum/CPIX#102]
Creating an issue under the CPIX repository for tracking.
The discussion is under this [issue](https://github.com/Dash-Industry-Forum/IOPv5/issues/18)

**Comment by lpiron** [comment]
Adding the ContentProtection@robustness and the OutputProtection is under the packager responsibility. Not to be added in the CPIX document.
No action needed.

**Comment by sergiofagostinho** [comment]
Hi @lpiron , I've been following the discussion under the IOP v5 issue.
While I agree that the it's under the packager responsibility to write those elements, the packager will still need to obtain that information. What happens if in the architecture that information flows via the Key Server? Should the packager perform an out-of-band request to obtain that information, or should the Key Server add a (proprietary) extension to CPIX to provide such information to the packager?

**Comment by lpiron** [comment]
During the discussion, we came to the conclusion that the key server cannot be the source for this information. The key server provides content key and data for these keys (encryption mode, DRM signaling for acquiring the key for the selected DRMs). The required robustness level for a DRM and the output protection rules are to be defined by another server.

**Comment by nicoweilelemental** [comment]
@lpiron I'd like to re-open the discussion. Even if the key server doesn't have the information, he can get it from the license service, as CPIX documents are designed to be augmented by multiple chained entities (https://dashif.org/docs/CPIX2.3/Cpix.html#usecase-incremental-authoring).

I still think we need a solution to add in CPIX what's needed to populate the ContentProtection@robustness, attribute as well as the OutputProtection element. And the way to do it is precisely the incremental authoring approach. If we don't do it, the packager doesn't have a way to create the required manifest signaling.

**Comment by lpiron** [comment]
Added in CPIX 2.4
