### ISSUE TITLE
Labeling enhancement proposal

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/CPIX#13]
Submitter: Thomás Inskip
Email: tinskip@google.com
During CPIX 2.0 development, it was assumed that the labels would be pre-agreed upon between various parties. However, in the process of implementing CPIX with an external partner, we have found this to be a shortcoming. Consider labels such as "HD+HDR", or "UHD+HDR+HFR".  It is much more practical for a content provider to specify how these labels are assigned during packaging in the CPIX document, and then use the same document to specify the keys to be used for licensing, only specifyig which keys should be included in a license by label; than having to agree ahead of time on the labels, or reference the keys by key ID when generating the license.  In short, it allows the provider / CPIX user to define and use arbitrary labels.

The proposed change would be to add an optional "@label" or "@assignLabel" to either the KeyUsageRule element or the ContentKey element. I believe it makes more sense in KeyUsageRule, as it assigns both a label and a key ID, which may or may not map 1:1. It may also be used in conjunction with LabelFilter for mapping / swapping labels if desired.

**Comment by sandersaares** [comment]
@tinskip, do I understand it right that the goal of this proposal is to eliminate the need for an authorization server to say "I authorize use of keys A, B and C" and instead to say "I authorize use of keys for content that matches the HD+HDR content key context"?

I see the value in that - having a single place where questions like "what is UHD" are resolved. I will attempt to work through the logic in my head and write down my thoughts. What needs are currently unsolved here? I can think of the following:

1. Packager does not necessarily know what labels go with what content. It cannot tell the difference between UHD and SD unless you specify it using the content-inspection rules of CPIX or unless it has its own logic to do the equivalent.
1. License server does not necessarily know what "I authorize HD+HDR" means - it just deals with specific key IDs. It does not even have content to inspect.
1. Given the above, the authorization service needs to provide key IDs to the license server in its authorization token or equivalent. It does not have the content to inspect, so there needs to be some database where a previous step wrote what key IDs go with what content.

Working backwards, we can see that either the license server or the authorization service needs to go from "HD+HDR" to a set of key IDs - this is unavoidable. One or the other needs to be provided input for doing this conversion. This input could be from:

* Some custom database.
* Possibly a CPIX document (if the format were so enhanced)
* Or perhaps something else entirely

This data will be unique for each piece of content (as the key IDs are unique), needs to be authenticated to prevent tampering and needs to be generated by a party trusted to make such decisions. I will assume this data is used by the authorization service to convert to key ID form, as that service is full of business logic anyway and probably the best place for this, as well.

What will this trusted party authorized to define this data be? Well, whatever decides "HD+HDR is to use key ID X" in the first place. This will be some business logic that writes such a statement into CPIX or another content processing format.

What would actually use this data?

* The packager would just use the content-inspection rules that are both the source of key ID mapping to content key content and, if the proposal were implemented in CPIX, the source of labeling of said content key context. It does not need to use the labels, though, in this situation.
* The authorization service would run custom business logic that says "this user is authorized for HD+HDR" and would then need this data to convert it to key IDs for the license server. If implemented in CPIX, it would need the relevant CPIX document from somewhere (maybe a database, maybe attached to the HTTP request, maybe something else - does not matter much). It would look for the key usage rules matching the label and select the key IDs referenced therein.

That makes sense in my head but please correct me if you meant something else entirely.


Scope creep was a concern with CPIX 2.0 and so we should be careful here. It feels like a suitable addition to me, though, without seriously jeopardizing the scope.

I would view such a feature as separate from labeling, however, because the term would get too overloaded. The optimal view I can think of right now would be to allow each key usage rule (defining each content key context) to be given a `@name`. The *name* is what the CPIX document defines, whereas *labels* remain something for 3rd parties to define and they need not even map 1:1 in cardinality.

The authorization service can be given the names of the content key contexts to authorize, plus the CPIX document, so it can map to key IDs. The packager and anything else would ignore the name entirely. This seems to result in a minimal-complexity enhancement that avoids disrupting any existing concepts already defined.

**Comment by tinskip** [comment]
Sander, your understanding of the use case is correct. The same CPIX document which is used to encrypt and package the content can be used to instruct the DRM server to generate a license given the CPIX doc and a list of "track labels" without having to pre-establish the meaning of these labels or know about the key IDs.

As far as how to convey these owner / provider defined values, using a KeyUsageRule@name isn't ideal because the term "track label" and "track type" are well established. In addition, using a KeyUsageRule attribute does not allow for a many-to-one mapping. Mutliple rules could conceivably map to the same value.

Perhaps an <AssignLabel> sub-element? It could be made mutually exclusive with LabelFilter. Or with semantics to replace the values matched in LabelFilter with AssignLabel.

This functionality could also be accomplished by using ContentKey@id as the "track label", possibly also assigning the same value to the corresponding AdaptationSet@id.  But I think it may be worth making this explicit. If not in the usage rule, then as an attribute of ContentKey.

**Comment by tinskip** [comment]
That was an <AssignLabel> element I was referring to in the third paragraph.  I don't know where it went.

**Comment by sandersaares** [comment]
I see what you mean by the many-to-one thing. As an easy example, with key periods, you would have a KeyUsageRule per key period but still the same "track type". So in essence it boils down to a non-unique decoration on the usage rule.

I would still keep it separate from the LabelFilter, as there is really not much common there (beyond the fact that both deal with types of labeling). It seems very much "decorative metadata", so I feel it should not affect the existing CPIX usage rule functionality in any way, just be a signal for identification of groups of usage rules.

X.509 has "key usage" attributes. Perhaps we could follow the same principle? `KeyUsageRule/IntendedUsage@trackType` or similar?

**Comment by tinskip** [comment]
I don't know that we necessarily need a whole new element for this purpose. We may extend it in the future, but for now I think KeyUsageRule@trackType would suffice.  WDYT? (we may have discussed this already).

**Comment by lpiron** [comment]
Integrated in Draft 7.
