### ISSUE TITLE
Request to clarify intended usage of CPIX transfer protocol

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/CPIX#15]
Submitter: Maxim Shevchenko
Email: maxim.shevchenko@irdeto.com
Section "6 Transfer Protocol" defines the preferred method for CPIX messages exchange. Section defines 4 HTTP methods that can be implemented there:
POST -> Behaviour: The request to create copyProtectionData for an encryptor.
GET -> Return copyProtectionData for the referenced CPIX_ID.
PUT -> Update copyProtectionData referenced by the CPIX_ID.
DELETE -> Delete/purge copyProtectionData referenced by the CPIX_ID.

The section gives a global overview, but at the same time is not resolving possible confusion over usage of proposed methods. I think that section needs to be accompanied by examples how proposed methods can be applied to different use cases. Example use cases can be: 
- taken from the guidelines itself, like 2.4.6 Incremental Update and Extension of the Document and applied to a proposed protocol
- applied to a real-world application, like the key exchange between encoder/packager and DRM systems

**Comment by sandersaares** [comment]
Perhaps we can take this as a signal that we need to do a deeper review of section 6 in general. What I see in practice is that it is ignored and people create their own proprietary protocols for this type of thing.

This is quite understandable as there is a lot of service-specific logic around CPIX processing. Is there even a valid use case for some type of generic transfer protocol? Something that a CPIX implementor actually plans to ever implement? If so, we should describe it in detail.

Alternatively, we could deprecate this part of CPIX if we find that there is no meaningful use case for some generic transfer protocol.

How is it that this section came to be? I am not aware of its history.

**Comment by karlg-arris** [comment]
Hi All,

We have an implementation of a key management system deployed that exposes CPIXF via the aforementioned transfer protocol.

Whilst there is, for sure some, confusion over the interpretation of some of the HTTP methods I think that deprecating this section is not the right course  - especially if the end goal is enabling (via the spec) interoperability between conforming content packaging systems and key management systems. 

Having a consistent and defined HTTP transfer protocol (Verbs, resource paths..etc) means that we can (potentially) avoid custom integrations with each packager system and vice versa.  Even if a packager vendor sees this implementing this specification as, initially, a customisation to their existing solution  - hopefully it can be justified by in someway guaranteeing that compatibility with other implementations of the spec is assured  

The biggest ambiguity we have right now is around the UPDATE verb - I think that maybe going by HTTP semantics, one could assume that the request wishes to update (change) key material associated with a specific CPIX_ID  - this not a good idea in my view since the only outcome I can envisage here involves some serious data integrity issues.

Perhaps UPDATE should be explicitly defined as requiring it key management system to update the CPIXF document itself?  The use-case here would be a solution in which there are more than one key management systems deployed, each controlling a subset of required DRM schemes. The document can be passed to each end point and they can append the relevant copyProtection. 

To provide some insight into other use cases for the transfer protocol 

POST  - This allows for the key 'push' mode concept.  Useful again for interoperability (key sharing) between compliant key management systems. In this case a 3rd party 'broker' generates keys and posts them to multiple key management systems in order to get the required copyProtectionData.

GET  - obvious 

DELETE  - We implemented this in response to a customers request that they be able to re-encrypt content with new keys.  Can also be useful for debugging.  


Hopefully this helps with the discussion

**Comment by karlg-arris** [comment]
All,

I looked at the updated transfer protocol draft.

As well as some general comments, I have some concerns around the POST verb usage since it doesn't seem to cover the key material 'push' mode that is referenced elsewhere in the doc.

Where is the best place to discuss this in general ?

Thanks,
Karl.

**Comment by sandersaares** [comment]
At the F2F we decided that the best way to continue with this topic would be to refactor the transfer protocol subject as a set of informative examples, given that it would be quite difficult to express a transfer protocol in any normative way that still makes sense considering the broad extent of business logic flexibility that must be allowed for in this regard.

This is from memory; I assume @lpiron has more authoritative minutes of the discussion.

**Comment by lpiron** [comment]
From the minutes of the meeting:
The agreement is that describing the flows of data is valuable but there are already existing APIs, hence there is no strong point in mandating a new one in the document. A CR is expected showing the workflows (packager-DRM server taking into account which entity creates the key ids, keys, DRM data) and proposing the API as an example only.

**Comment by sandersaares** [comment]
After reviewing the latest circulated transfer protocol examples draft I post here some comments.

I find the proposed chapter/document in its current form to be difficult to consume. There is potential value in offering API design and architecture guidelines but this should be clearly reflected in the structure of the document. At the moment it is just a sequence of examples in various forms, which can be hard to read and understand in the proper context (examples of what? why? etc.).

In ideal form, I would see it directly expressed as a set of well-documented design patterns, along the lines of those found in the [Microsoft Patterns & Practices series](https://docs.microsoft.com/en-us/azure/architecture/patterns/category/resiliency).

Each design pattern could be attributed with motivation, constraints, implementation guidelines and examples.

Given that a lot of the context and motivation for each example is missing, I think it is too early to go into the specifics of reviewing the exact patterns proposed (we would likely just be speaking past each other, coming to it with different mindsets). Once the design patterns are better contextualized, I think more in depth discussion can be had.

Trying to scan the existing proposal, I see hints of the following design patterns surfacing:

* Template document - one party creates a template document, the other fills it in.
* The chapters about URLs are presumably intended to represent some design pattern but I am unable to distill what exactly this pattern is meant to be (obviously there is a pattern in the URLs but I assume it is supposed to be something more substantial on a conceptual level).

**Comment by lpiron** [comment]
Closed as all discussion on transfer protocol are to be made in a new repository [https://github.com/Dash-Industry-Forum/CPIX-Transfer-Protocol](url)
