### ISSUE TITLE
Request to allow special characters to be included in asset identifier

### ISSUE THREAD

**Issue by spuppala** [Dash-Industry-Forum/CPIX#18]
We have been using the “id” attribute of CPIX element to represent the assetId. But according to CPIX schema definition it is of type "xs:ID", defined as:
_An xsd:ID value must be an NCName. This means that it must start with a letter or underscore, and can only contain letters, digits, underscores, hyphens, and periods._

But we are not sure if it a good idea to be using this type to represent the assetId as it can contain special characters like ‘&’ or may be all numeric etc.,

**Comment by sandersaares** [comment]
One of the reasons for not allowing freeform strings in the `@id` attribute is that there are common XML processing libraries that assume any `@id` attribute is of the `xs:id` data type. Allowing more flexible data would lead to compatibility issues with such libraries.

I believe this is also why we use `@kid` to uniquely identify content keys, instead of using `@id`. Would something like an `@assetId` attribute of the unrestricted string data type on the root element satisfy your use case?

**Comment by spuppala** [comment]
Yes, that would be good.

**Comment by tinskip** [comment]
I agree this is needed.  My choice would be CPIX@contentId.

We do way in the spec, that the "id" can be the content ID, but this seems insufficient.

**Comment by psimax** [comment]
It will be good if it will support [CRID](https://en.wikipedia.org/wiki/Content_reference_identifier) notation

**Comment by lpiron** [comment]
text added in draft 3, please review

**Comment by fertunc** [comment]
How can I access draft versions? Thanks!

**Comment by lpiron** [comment]
This is available here http://files.groupspaces.com/dashif/files/2075902/DASH-IF-CPIX-v2.1-Draft4-WithKeyHierarchies.docx

**Comment by fertunc** [comment]
Thank you for your help Laurent. Description for assetId in draft document looks good and addresses the request.

**Comment by lpiron** [comment]
Closed following general agreement for the solution.
