### ISSUE TITLE
Few DRM specific information missing in CPIX response

### ISSUE THREAD

**Issue by shobanaberlin** [Dash-Industry-Forum/CPIX#60]
Though the CPIX API standardises the communication between the DRM system and the manifest creator and makes information like PSSH available in the manifest, there are still DRM specific information like
1)schemeIdUri, an attribute of contentprotection element
2)XML namespace for the DRM 
which has to be included in the manifest. But they are not part of CPIX standard today. Can someone please help understand how this information could be made available in the manifest without the CPIX response having it.

**Comment by shobanaberlin** [comment]
The ContentProtectionData doesnt seem to be mandated, unfortunately the DRM vendor that we are integrating with donot have this data in the response. Do you think the ContentProtectionData should be mandated if the format is DASH?

**Comment by sandersaares** [comment]
The CPIX format is deliberately made to be very flexible because we did not believe we could accurately foresee all the possible use cases. As such, very little in the CPIX document is mandatory - only the mere basics that are necessary to process it.

I recommend you ask your DRM vendor to add the data that you need.

**Comment by lpiron** [comment]
Closing as questions have been answered and no further comments received
