### ISSUE TITLE
Mapping from Label Filter entry to audio/video filter entry

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/CPIX#82]
It would be helpful if for a subset of commonly used strings (HDR, HFR, HD,SD, AUIO_STEREO) for label filter some details were given how that would map to videofilter or audiofilter instantiations. Right now any string that is pre-agreed between producer and consumer can be used, but this makes it hard to make requests interoperable without defining some of these keywords for the label filter based on corresponding AV properties. It would be helpful for interoperability if for some of the keywords this was explicitly defined in the specification. If this is agreed upon we can provide relevant specification text to make this mapping to av properties.

**Comment by sandersaares** [comment]
We discussed this in a call but looks like did not write any comment here. I will try to reconstruct from memory.

The label filter is intentionally left entirely open for implementations to define, without any predefined labels.

For all the scenarios you mention `HDR, HFR, HD,SD, AUIO_STEREO` there exist specialized filters like `VideoFilter` and `AudioFilter` that should be used instead of labels.

**Comment by RufaelDev** [comment]
yes right now AudioFilter or VideoFilter can be used, because in practice people don't want to pre-define these labels, and will stick only to that. I think defining some labels based on audiofilter or videofilter still makes sense.
