### ISSUE TITLE
Encryption in DASH

### ISSUE THREAD

**Issue by azeemmohd** [Dash-Industry-Forum/CPIX#84]
Hi,

I had the following questions around Encryption in DASH protocol, and would be grateful for your help with them:

1) Does the DASH Protocol, allow for keeping raw keys themselves, instead of specifying a key acquisition url, for the encrypted content within the manifest?

2) What is the difference between Common Encryption, and Segment Encryption?

Specifically, I am looking to understand what would be the pros/cons of using an encryption descriptor  for Segment Encryption like this:

```
<sea:SegmentEncryption schemeIdUri="urn:mpeg:dash:sea:aes128-cbc:2013"/>
<sea:KeySystem keySystemUri="urn:mpeg:dash:sea:keysys:http:2013"/>
<sea:CryptoPeriod
  keyUriTemplate="https://wamsamsclus001kd-hs.cloudapp.net/?KID=XXXXXXXXXXX"
  IV="XXXXXXXXXXXX"/>
```

Vs
```
      <!-- MPEG Common Encryption -->
      <ContentProtection schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc" cenc:default_KID="XXXXXXXXXXXXXXXXXX"/>
      <!-- Clear Key -->
      <ContentProtection schemeIdUri="urn:uuid:e2719d58-a985-b3c9-781a-b030af78d30e" value="ClearKey1.0">
        <ckey:Laurl Lic_type="EME-1.0">http://abc.com?key</ckey:Laurl>
      </ContentProtection>
```

Thanks for your help in advance!

**Comment by lpiron** [comment]
1. Does the DASH Protocol, allow for keeping raw keys themselves, instead of specifying a key acquisition url, for the encrypted content within the manifest?
> Not as part of the defined namespaces, but there are two options for this not recommended way of delivering keys
   a. Use W3C clear key mechanism defined in EME that allows getting unprotected content keys from an HTTP request. DASH-IF IOP defines how to embed the URL in a ContentProtection element with a DRM System ID registered at dashif.org
   b. Use a ContentProtection element with some proprietary XML elements. These extensions can carry the keys in the clear (you could use the pskc XML elements there - RFC 6030, CPIX specification does extend the keyType element for carrying content keys and one option is to have content keys in the clear). You need to have a dummy DRM system ID.

One more time, not recommended to do this. Depending on your use case, CPIX may be a better way for exchanging content keys (between a packager and DRM license server for example), CPIX allows having protected or in the clear content keys.

2. What is the difference between Common Encryption, and Segment Encryption?
> Segment encryption encrypts everything including header. This is comparable to the AES-128 encryption in HLS. This is not parser and demux friendly as content must be decrypted before been provided to the rendering pipe. Common Encryption (CENC) is only encrypting the data in the mdat box (different modes are possible and also sub-sample encryption is supported). Decryption can be integrated in the rendering pipe after demux. CENC is Secure Media Path friendly while segment encryption is not. These are two completely different ways for encrypting a file. 
Regarding your question on the XSD, not sure to understand what you want to achieve with the elements you mention and I do not understand where you would put the different elements from the sea namespace in a MPD.

**Comment by kunalgoelgh** [comment]
@lpiron 

Thanks a lot for explaining the difference between CENC and SEA.

A few follow-up questions?
1) SEA and AES128 bit encryption is considered as envelope encryption. From documentation, as i understood envelope encryption is when a DEK is encrypted further with a KEK, which is shared with the client.
    Here, is CENC with HTTPS being used for LicenseAuthenticationUrl also considered as envelope encryption?

2) Can you please elaborate on the comment for "Secure Media Path friendly". 

3) For CENC, since only the data in the mdat box is being encrypted, wanted to understand the implications of the same. Is this less secure, or open to attacks?
    Similarly for SEA, is the use of DRM mandated? In that case if the player is handling decryption, then is it considered less secure?

Thanks in advance for your help on the same :).

**Comment by lpiron** [comment]
1. SEA and AES128 bit encryption is considered as envelope encryption. From documentation, as i understood envelope encryption is when a DEK is encrypted further with a KEK, which is shared with the client. Here, is CENC with HTTPS being used for LicenseAuthenticationUrl also considered as envelope encryption? If not, can we acheive envelope encryption via CENC? (Certain DRM's do implement this. Wanted to check if say ClearKey can do the same.)

My understanding of envelope encryption is that everything is encrypted, it is not possible to know what the format of the content is before decrypting. It is independent from how content keys are delivered or protected. To answer your question, CENC with HTTPS is not envelop encryption. CENC allows to know that content is ISOBMFF, what are the tracks and so on.

2. Can you please elaborate on the comment for "Secure Media Path friendly".

Hardware implementation can completely protect the content while been process. The entry point is the encrypted muxed content and the output is either an embedded screen or an HDMI output (protected by HDCP). The only pieces of software that can interact with content while in this protected path are to be in the TEE (Trusted Execution Environment), software is signed and so on. This path can be called the Secure Media Path. If content needs to be decrypted before (simply for knowing what it is) then it is not protected anymore by the hardware.

3. For CENC, since only the data in the mdat box is being encrypted, wanted to understand the implications of the same. Is this less secure, or open to attacks?

No, it is not. The relevant information (video and audio is encrypted), what is not encrypted is not critical.

4. Similarly for SEA, is the use of CDM mandated? In case it not, and if the player is handling decryption, then is it considered less secure?

Not sure to understand this question

**Comment by azeemmohd** [comment]
Thanks @lpiron; - your response have been of huge help. Closing this issue.
